# Generated by Django 5.2.7 on 2025-10-21 17:58

import patents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='file_type',
            field=models.CharField(choices=[('OBJ', 'Wavefront OBJ'), ('STL', 'Stereolithography'), ('STP', 'STEP File'), ('IGES', 'IGES File')], help_text='Type of the 3D model file', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='related_files',
            field=models.JSONField(blank=True, help_text='Paths to related files (MTL, textures, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_file',
            field=models.FileField(help_text='Upload a 3D model file (.obj, .stl, .stp, .iges) or a ZIP containing an OBJ with its MTL and texture files', upload_to=patents.models.get_upload_path, validators=[patents.models.validate_patent_file]),
        ),
    ]
