# Generated by Django 5.2.7 on 2025-10-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0002_patent_file_type_patent_related_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='patent_file',
        ),
        migrations.AddField(
            model_name='patent',
            name='storage_path',
            field=models.CharField(blank=True, help_text='folder containing model files', max_length=255, null=True),
        ),
    ]
