# Generated by Django 5.2.7 on 2025-10-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0003_remove_patent_patent_file_patent_storage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='thumbnail_path',
            field=models.CharField(blank=True, help_text='Path to the thumbnail image', max_length=255, null=True),
        ),
    ]
