# Generated by Django 5.2.7 on 2025-10-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0004_patent_thumbnail_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='model_filename',
            field=models.CharField(blank=True, help_text='Original model filename', max_length=255, null=True),
        ),
    ]
