# Generated by Django 5.2.7 on 2025-12-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0005_patent_model_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='glb_file_path',
            field=models.CharField(blank=True, help_text='Path to the converted GLB file', max_length=255, null=True),
        ),
    ]
