"""initial

Revision ID: e073c0265fdf
Revises: 
Create Date: 2026-04-19 16:01:18.613588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e073c0265fdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patents_patent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('OBJ', 'STL', 'STP', 'IGES', 'GLB', 'FBX', name='filetype_enum'), nullable=True),
    sa.Column('model_filename', sa.String(length=255), nullable=True),
    sa.Column('zip_file_path', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('related_files', sa.JSON(), nullable=True),
    sa.Column('glb_file_path', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('conversion_status', sa.Enum('UPLOADED', 'IN_PROCESSING', 'CONVERTED', 'FAILED', name='conversionstatus_enum'), nullable=False),
    sa.Column('conversion_error', sa.String(length=2000), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_patent_user_id'), 'patents_patent', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patents_patent_user_id'), table_name='patents_patent')
    op.drop_table('patents_patent')
    op.drop_table('users_user')
    sa.Enum(name='conversionstatus_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='filetype_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
