"""add locarno_main_class + locarno_subclass tables; seed; FK from patents_patent

Revision ID: e6c1f4a23bd9
Revises: d3a9b71f08e2
Create Date: 2026-05-12 00:00:00.000000

Replaces app-layer string validation with DB-enforced FKs, so a future admin
panel can curate the Locarno tree without code deploys.

Seed source: fastapi_app/app/data/locarno_seed.json (generated by
scripts/build_locarno.py from the WIPO/Turkpatent XLS).
"""
import json
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "e6c1f4a23bd9"
down_revision: Union[str, None] = "d3a9b71f08e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SEED_PATH = Path(__file__).resolve().parents[2] / "app" / "data" / "locarno_seed.json"


def _load_seed() -> dict:
    with SEED_PATH.open(encoding="utf-8") as f:
        return json.load(f)


def upgrade() -> None:
    # -- 1. Create lookup tables ---------------------------------------------
    main_table = op.create_table(
        "locarno_main_class",
        sa.Column("value", sa.String(length=32), primary_key=True),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("sort_index", sa.Integer(), nullable=False, server_default="0"),
        sa.UniqueConstraint("number", name="uq_locarno_main_class_number"),
    )
    sub_table = op.create_table(
        "locarno_subclass",
        sa.Column("value", sa.String(length=255), primary_key=True),
        sa.Column("main_class_value", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=512), nullable=False),
        sa.Column("locarno_id", sa.Integer(), nullable=True),
        sa.Column("sort_index", sa.Integer(), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(
            ["main_class_value"],
            ["locarno_main_class.value"],
            name="fk_locarno_subclass_main_class",
            onupdate="CASCADE",
            ondelete="RESTRICT",
        ),
    )
    op.create_index(
        "ix_locarno_subclass_main_class_value",
        "locarno_subclass",
        ["main_class_value"],
    )

    # -- 2. Seed --------------------------------------------------------------
    seed = _load_seed()
    if seed["main_classes"]:
        op.bulk_insert(main_table, seed["main_classes"])
    if seed["subclasses"]:
        # Insert in chunks — some Postgres deployments choke on multi-thousand
        # row bulk_insert payloads buffered in memory.
        rows = seed["subclasses"]
        chunk = 500
        for i in range(0, len(rows), chunk):
            op.bulk_insert(sub_table, rows[i : i + chunk])

    # -- 3. Reshape patents_patent locarno columns ----------------------------
    # Previous migration created them NOT NULL with server_default='' so old
    # rows backfilled cleanly. Now we want real FK integrity — drop NOT NULL
    # FIRST (otherwise UPDATE-to-NULL is rejected), then null out the tombstone
    # '' values, then drop the server_default.
    op.alter_column(
        "patents_patent",
        "locarno_main_class",
        existing_type=sa.String(length=32),
        nullable=True,
    )
    op.alter_column(
        "patents_patent",
        "locarno_subclass",
        existing_type=sa.String(length=255),
        nullable=True,
    )
    op.execute(
        "UPDATE patents_patent SET locarno_main_class = NULL WHERE locarno_main_class = ''"
    )
    op.execute(
        "UPDATE patents_patent SET locarno_subclass = NULL WHERE locarno_subclass = ''"
    )
    op.alter_column(
        "patents_patent",
        "locarno_main_class",
        existing_type=sa.String(length=32),
        server_default=None,
    )
    op.alter_column(
        "patents_patent",
        "locarno_subclass",
        existing_type=sa.String(length=255),
        server_default=None,
    )
    op.create_foreign_key(
        "fk_patents_patent_locarno_main_class",
        "patents_patent",
        "locarno_main_class",
        ["locarno_main_class"],
        ["value"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_patents_patent_locarno_subclass",
        "patents_patent",
        "locarno_subclass",
        ["locarno_subclass"],
        ["value"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    op.drop_constraint("fk_patents_patent_locarno_subclass", "patents_patent", type_="foreignkey")
    op.drop_constraint("fk_patents_patent_locarno_main_class", "patents_patent", type_="foreignkey")
    # Restore the previous NOT NULL + '' default so the chain stays consistent.
    op.alter_column(
        "patents_patent",
        "locarno_main_class",
        existing_type=sa.String(length=32),
        nullable=False,
        server_default="",
    )
    op.alter_column(
        "patents_patent",
        "locarno_subclass",
        existing_type=sa.String(length=255),
        nullable=False,
        server_default="",
    )
    op.execute("UPDATE patents_patent SET locarno_main_class = '' WHERE locarno_main_class IS NULL")
    op.execute("UPDATE patents_patent SET locarno_subclass = '' WHERE locarno_subclass IS NULL")

    op.drop_index("ix_locarno_subclass_main_class_value", table_name="locarno_subclass")
    op.drop_table("locarno_subclass")
    op.drop_table("locarno_main_class")